/*
ABOUTME: Configures development and production builds for the Obsidian plugin bundle.
ABOUTME: Keeps Node builtins external so the output only contains browser-safe plugin code.
*/
import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "process";

const externalNodeModules = Array.from(
	new Set(
		builtinModules.flatMap((moduleName) => [moduleName, `node:${moduleName}`])
	)
);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	loader: {
		".png": "binary",
	},
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...externalNodeModules,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
